### ISSUE TITLE
Doesn't work with Subnautica 2.0

### ISSUE THREAD

**Issue by miasik** [AndreaDev3D/SubnauticaMod#2]
Could you please update the mod for Subnautica 2.0?

**Comment by AndreaDev3D** [comment]
Not sure when, but if I will have some spare time, I will try.

**Comment by AndreaDev3D** [comment]
Porting is in testing if you want to try it:
https://github.com/AndreaDev3D/SubnauticaMod/releases/tag/v1.0.2.0-alpha
